import { Component, OnInit } from '@angular/core';
import { IPerson } from 'src/app/models/IPerson.model';

@Component({
  selector: 'app-event-speaker',
  templateUrl: './event-speaker.component.html',
  styleUrls: ['./event-speaker.component.css'],
})
export class EventSpeakerComponent implements OnInit {
  speakers: IPerson[] = [
    {
      id: 1,
      image: 'assets/speakers/mohit-gulati.jpeg',
      name: 'Mohit Gulati',
      company: 'Google',
      designation: 'Product Manager',
      twitter: '',
      linkedin: 'https://www.linkedin.com/in/mohitgulati/',
      instagram: '',
      bio: 'Product Leadership | Product Management | Enterprise | SaaS | Agile | UI/UX | APIs | Go-To Market | Product Launch | Application Data Management | Data Governance | Big Data | Reporting | Dashboards | FinTech | Payments | Banking | Startups | Team Building',
    },
    {
      id: 2,
      image: 'assets/speakers/jitendra-gupta.jpeg',
      name: 'Jitendra Gupta',
      company: 'GCP',
      designation: 'Google Developer Expert',
      profile: 'https://medium.com/@jitu028',
      twitter: 'https://x.com/jitu028',
      linkedin: 'https://www.linkedin.com/in/jitu028/',
      instagram: '',
      bio: 'I am a seasoned GCP Cloud Architect with over 12 years of experience in the IT industry, specializing in enterprise architecture and multi-cloud environments. With 13,000 LinkedIn connections and a top 1% ranking on Topmate, I have guided and inspired over 4,000 individuals to learn and actively contribute to the Google Cloud community. My experience includes speaking at 20+ public technical forums, with a strong presence at over 10 Google Cloud community platforms. I have authored 30+ high impact Medium articles (~500 followers) and delivered comprehensive Google Cloud Fundamentals training, which is accessible to all on my YouTube channel. Additionally, I am developing a use case for test case generation using Gemini AI and have created the Terra-GCP-CLI tool, which automates Terraform code generation and troubleshooting via CLI.',
    },
    {
      id: 3,
      image: 'assets/speakers/rishiraj-acharya.jpeg',
      name: 'Rishiraj Acharya',
      company: 'AI/ML',
      designation: 'Google Developer Expert',
      profile: '',
      twitter: 'https://twitter.com/rishirajacharya',
      linkedin: 'https://linkedin.com/in/rishirajacharya',
      instagram: '',
      bio: 'Rishiraj is a GCP Champion Innovator & Google Developer Expert in ML (1st GDE from Generative AI & Keras sub-category in India). He is a Machine Learning Engineer at Intellitek, worked at Tensorlake, Dynopii & Celebal in the past and is a Hugging Face 🤗 Fellow. He is the organizer of TensorFlow User Group Kolkata and has been a Google Summer of Code contributor at TensorFlow. He is a Kaggle Competitions Master and has been a KaggleX BIPOC Grant Mentor. Rishiraj specializes in the domain of Natural Language Processing and Speech Technologies.',
    },
    {
      id: 4,
      image: 'assets/speakers/dhavalkaku.jpeg',
      name: 'Dhaval Kaku',
      company: 'Innovation Mission Punjab',
      designation: 'Program Coordinator',
      profile: '',
      twitter: '',
      linkedin: 'https://www.linkedin.com/in/dhavalkaku/',
      instagram: '',
      "bio": "I am Dhaval Kaku, an Entrepreneur-turned-Startup Ecosystem enabler with a passion for fostering innovation. My journey began in 2015 with GrungeTech, a music-tech venture that won multiple business plan competitions, including one at IIM Ahmedabad's CIIE. From 2018 to 2020, I managed programs at GTU Innovation Council, supporting 300+ startups under the SSIP initiative through mentorship, funding (₹3 Crore+), and market deployment assistance. I also launched 'Pitch It Right,' a flagship program to prepare startups for funding. In 2020, I contributed to AISEA, IIT Hyderabad's accelerator, helping startups raise ₹25 Crore+ and achieve 3x revenue growth. Currently, I serve as Acceleration Program Coordinator at Innovation Mission Punjab, driving 1500+ initiatives through capacity-building and business acceleration programs. Passionate about emerging technologies, I mentor startups, advise think tanks, and enjoy exploring innovative use cases on GPT platforms in my free time."
    },
    {
      id: 5,
      image: 'assets/speakers/burhanuddin-rashid.jpeg',
      name: 'Burhanuddin Rashid',
      company: 'Flutter & Dart',
      designation: 'Google Developer Expert',
      profile: '',
      twitter: 'https://www.twitter.com/burhanrashid52',
      linkedin: 'https://www.linkedin.com/in/burhanuddin-rashid-a16959b1',
      instagram: '',
      bio: 'I am an Open-Source enthusiast from India. Being a Software Craftsman I love to write clean and readable code and currently been working on Android, Kotlin and Flutter. I am a movie freak. I try to help, learn and share my knowledge by writing blogs or speaking at conferences.',
    },
    {
      id: 6,
      image: 'assets/speakers/chhavi-garg.jpeg',
      name: 'Chhavi Garg',
      company: 'Arexa & Bharat XR',
      designation: 'Co-founder',
      profile: '',
      twitter: 'https://x.com/chhaviGG',
      linkedin: 'https://www.linkedin.com/in/chhaviGG/',
      instagram: '',
      bio: 'Chhavi Garg is Co-Founder at BharatXR & Arexa. She is a passionate advocate for XR, AR, and Cloud technologies. With a mission to foster growth and innovation, she actively engages in tech communities, inspiring and empowering individuals to explore the endless possibilities of emerging technologies.',
    },
    {
      id: 7,
      image: 'assets/speakers/pranav.jpeg',
      name: 'Pranav Singh Parmar',
      company: 'iapp Technologies LLP ',
      designation: 'Mobile App Developer',
      profile: '',
      twitter: 'https://x.com/singhpranav1055',
      linkedin: 'https://www.linkedin.com/in/pranav-singh-parmar/',
      instagram: '',
      bio: `Experienced Mobile App Developer proficient in iOS, Android, Flutter, and React Native. Skilled in crafting efficient code with a focus on proper implementation and thorough documentation. A passionate Technical Speaker who enjoys sharing knowledge and insights with peers and aspiring developers. Committed to staying abreast of the latest updates and advancements in the field, ensuring the delivery of cutting-edge solutions.`,
    },
    {
      id: 8,
      image: 'assets/speakers/rohtash-sethi.jpeg',
      name: 'Rohtash Sethi',
      company: 'Secureworks ',
      designation: 'Senior Principal Software Engineer',
      profile: '',
      twitter: 'https://x.com/rohtashsethi',
      linkedin: 'https://www.linkedin.com/in/rohtashsethi/',
      instagram: '',
      bio: `Rohtash Sethi is Senior Principal Software Engineer at Secureworks. He brings over 9 years of expertise in building scalable, high-performance Single Page Applications (SPAs) using technologies like Angular, TypeScript, and TailwindCSS. With experience spanning sectors such as property management, cybersecurity, banking, and manufacturing, he excels in innovation, leadership, and continuous learning. A speaker at India’s largest Angular conference in 2024, Rohtash is also an active contributor to open-source projects and npm package development.`,
    },
  ].sort((a, b) => a.id - b.id);

  ngOnInit(): void {}
}
